# 4. Numpy

Numpy (acronym for "Numeric Python" or "Numerical Python") is a foundational, open-source library upon which all scientific programming in Python is based. At its core are tools for efficient creation and manipulation of data arrays (including matrices and tensors). Built upon these is an array of functions for manipulating these arrays, including advanced linear algebra routines optimised for processing very large matrices. 

We will start by importing the numpy module using its standard abbreviation '```np```'. Note, we only have to do this once for the entire notebook

In [2]:
#importing numpy
import numpy as np 

## 4.1 Starting with the basics

A numpy array looks similar to a list, in that it is represented by block of values. Indeed it is possible to initialise an array from a list (or nested list). However, for an array **all of the values must by of the same type** and **all the rows and columns (and higher dimensions) must have the same length**. 

Some examples where arrays are initialised from ```np.array()``` by passing it a list (or nested list) are shown below:

In [ ]:
# creating a numpy array 
my_array=np.array([1,2,3,4,5,6]) # constructing from a list

print('my array \n {}'.format(my_array))

# construction of matrix from a 2D list 
my_matrix=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]]) 
print('my matrix \n {}'.format(my_matrix))

Once created, each array object may be decribed by a range of attributes including ```shape``` (length of each dimension), ```size``` (total number of elements), ```ndim``` (total number of dimensions, ```dtype``` (the data type of the array)

In [ ]:

# printing attributes of array
print('array shape:', my_array.shape)
print('array size:', my_array.size)
print('array total dimensions:', my_array.ndim)
print('array data type:', my_array.dtype)

# printing attributes of matrix
print('matrix shape:', my_matrix.shape)
print('matrix size:', my_matrix.size)
print('matrix total dimensions:', my_matrix.ndim)
print('matrix data type:', my_matrix.dtype)


## 4.2 Creating arrays

Numpy also provides many functions to create arrays. The function ```zeros``` creates an array full of zeros; ```ones``` creates an array full of ones, ```eye``` creates and idenity matrix and ```empty``` creates an array of fixed shape with uninitialiased (_very_) small _non-zero_ values. Note that by default, the datatype (```dtype```) of the created array is float64 but this can be changed during initialisation.

In [ ]:
# creating a 3x3 matrix of all float zeros
zeros=np.zeros( (3,3) )
# creating a 3x3 matrix of all integer ones
ones=np.ones( (3,3), dtype=np.int16 )  # note how dtype can be specified
# creating a 3x3 indentiy matrix of float type
identity = np.eye(3)
# creating a 3x3 empty matrix of very small random values
empty=np.empty( (3,3) )            

# here '\n' forces a new line
print('zeros: \n {}'.format(zeros))
print('ones: \n {}'.format(ones))

print('identity: \n {}'.format(identity))

print('empty:\n{}'.format(empty))


Numpy also has array constructors that work similarly to the standard function ```range``` to create sequences of numbers. These include ```arange``` and ```linspace```. Here  ```arange``` is closest to ```range``` and best used for integer sequences. You can call arange with one number N to return intergers in the range 0 to N, or supply a start and end point, or even an interval:

In [ ]:
# integers from 0 to 5
range1=np.arange(5)
# integers from 5 to 10
range2=np.arange(5,10)
# integers from 50 to 80 in steps of 5 (note interval does not have to be an integer)
range3=np.arange(50,80,5)

print('range1: \n {}'.format(range1))
print('range2: \n {}'.format(range2))
print('range3: \n {}'.format(range3))


Alternatively, when looking for sets of evenly spaced numbers within some fixed range use ```np.linspace(start,end,num)```, where ```num``` determines the number of samples and thus the size of the spacing

In [ ]:
# create an array with all integers from 0 to 10
integer_range=np.arange(10)
# create 9 linearly spaced numbers from 0 to 2  
linearly_spaced_seq=np.linspace( 0, 2, 9 ) 

print('integer range:')
print(integer_range)

print('linearly space range:')
print(linearly_spaced_seq)

Finally, numpy has a submodule containing a range of random number generators to create arrays that follow specific random distributions i.e 

In [ ]:
# all creating matrices of shape (3,3) 
#random numbers in range [0.0, 1.0)
rand1=np.random.random((3,3)) 
#in range low (5) to high (20)
rand2=np.random.randint(5,20,(3,3))
# sampling random floats from the standard normal distribution
# note how dimensions are defined as separate arguments
rand3=np.random.randn(3,3) 

print('random numbers in range 0-1')
print(rand1)

print('random integers:')
print(rand2)

print('random floats drawn from standard normal distribution')
print(rand3)


Note ```np.random.random``` (input argument = tuple defining array size) creates a matrix of random variables by sampling from the continuous uniform distribution over the stated interval; np.random.randint(low,high=None,size=None, dtype=np.int) creates an array of random integers, defined in range _low_ to _high_ (if _high_ is not defined then the range runs from 0 to _low_); np.random.randn(d0, d1, ..., dn) draws samples from the standard normal distribution. Note how the array size is supplied from separate arguments for row and column dimensions, not as a single tuple (e.g. ```(3,3)```)!

For more examples see https://docs.scipy.org/doc/numpy/reference/routines.random.html

## 4.3 Loading from files

Often in this course we will use pre-generated array data saved in text files. Note that, rather than loading data line by line using Python standard functions, it is possible to directly load matrices and arrays from text files using the ```loadtxt``` function of numpy.

In [ ]:
new_mat=np.loadtxt('matrix.txt',delimiter=',') # note use of optional argument delimeter to load files with comma separated values
print(new_mat)

Matrices can be saved using ```savetxt```. By default the output is delimeted by spaces. You can also save using ```save```. This will save in ```.npy``` format. ```.npy``` formatting vastly improve the efficiency of reading and writing arrays. They can be loaded with ```load```

In [ ]:
# saving in npy format
np.save('matrix.npy',new_mat)
# loading in npy.format
new_mat2=np.load('matrix.npy')
print(new_mat2)

# Exercise 1: Creating numpy arrays

1. Try creating some arrays of your own using the nested list notation e.g: 
    
    - Create a numpy array with 6 integer values using function ```np.array```
    - Print the various attributes of this array: ```shape```, ```size```, ```ndim```, ```dtype```
    - Repeat for a float array and a string array
    - Create an 2D array with dimensions 3x2, print it's shape and dimensions
    - What about a 3D array (optional)?
    
2. Create a 3x4 array full of zeros (*hint* using ```np.zeros```)

3. Create a random 2x4 array of of random integers in the range 10 to 20 

4. Create an array that returns every even number from 0 to 20


In [7]:
# 1.1 To do - try creating arrays from 1D, 2D and 3D nested lists, print attributes
A=np.array([1,2,3,4,5])
B=np.array([[1,2,3],[4,5,6],[7,8,9]])

print('shape of A: {} , B: {}'.format(A.shape,B.shape))
print('size of A: {} , B: {}'.format(A.size,B.size))
print('number of dimensions of A: {} , B: {}'.format(A.ndim,B.ndim))

# 1.2.  Create a 3x4 array full of zeros
my_zeros=np.zeros((3,4))
print('my zeros: \n{}'.format(my_zeros))
# 1.3 Create a random 2x4 array of of random integers in the range 10 to 20 
my_randint=np.random.randint(10,20,(2,4))
print('my randint: \n{}'.format(my_randint))
# 4. Create an array that returns every even number from 0 to 20
my_evens=np.arange(0,21,2) # note not inclusive of last number in range

print('my evens: \n{}'.format(my_evens))


shape of A: (5,) , B: (3, 3)
size of A: 5 , B: 9
number of dimensions of A: 1 , B: 2
my zeros: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
my randint: 
[[14 18 16 18]
 [17 18 10 18]]
my evens: 
[ 0  2  4  6  8 10 12 14 16 18 20]




## 4.4 Indexing Slicing and Iterating

Arrays, like lists are indexed from 0:

In [ ]:
my_array=np.array([1,2,3,4,5,5,6,7,9,10])

print('the first index of array:',my_array[0])
print('the last index of array:',my_array[-1])
print('the penultimate index of array:',my_array[-2])



Similar to Python lists, numpy arrays can be sliced. You must specify a slice for each dimension of the array:

In [ ]:
my_matrix=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]]) #redfined from above

print('my_matrix=',my_matrix)
# to return a whole row (with all columns); specifically the first row
print('the first row ', my_matrix[0,:])
# to return a whole column (with all rows); specifically the fourth column (indexed by 3)
print('the fourth column (and all rows)', my_matrix[:,3])

print('the sub-matrix given by columns 2 and 3 : ')
#this returns all rows with ':' and then the columns corresponding to the first and second index (not the third
# as the slice is not exclusive of the last index in the range)
print(my_matrix[:,1:3]) 

Similarly to list slicing the range is non inclusive of the last index in the range. Use of ```:``` on its own will return all indices (columns/rows etc) for that dimension of the array.

While slicing extracts sub-matrices in fixed ranges, integer indexing (using lists) allows arbitrary values to be selected from the array:

In [ ]:
#. this slice will extract one row (corresponding to index 0), and 3 columns (corresponding to indices 1,3 and 5)
print('row 1 and Columns 2 4 and 6', my_matrix[0,[1,3,5]])

It is also possible to return all indices from a array, whose values meet certain boolean conditions e.g.

In [ ]:
boolean_cond=(my_matrix>4)
print('Return all indices correponding to values from my_matrix that are > 4:')
print(boolean_cond)

This can be useful, when for example the goal is to mask one array using the values of another:

In [ ]:
my_matrix2=np.array([[11,12,13,14,15,16],[17,18,19,20,21,22]]) #redfined from above
#this will mask matrix2 to return the values at indices where boolean_cond==True
print(my_matrix2[boolean_cond])

## 4.5 Changing the shape of an array

In some occasions over the course it will become necessary to reshape or flatten an array before performing operations on it. There are several inbuilt functions in numpy for this purpose. Array flattening can be achieved using ```flatten``` or ```ravel```. Whereas, general reshaping can instead be achieved with ```reshape``` or ```resize```. Let's look at both in more detail:

### 4.5.1 Flattening matrices/tensors into one long vector

The two functions (```ravel``` and ```flatten```) perform the exact same operation but whereas ```flatten``` creates a complete copy of the variable (with new shape) in memory ```ravel``` continues to reference the original array. This makes ```ravel()``` faster than ```flatten()``` as it does not occupy any memory; however it may result in undersired behaviour (as shown below).

In both cases the functions offer choices as to how the array is unravelled (through an optional argument "order"). Order can have the values "C" (default), "F" and "A". Here, "C" means to flatten in the same way as would be performed in C/C++ i.e. in row-major ordering such that the row index varies the slowest, and the column index the quickest. "F" stands for Fortran column-major ordering and "A" means preserve the C/Fortran style of the original array (where this is saved as an attribute when the array is created).

In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) 
print(A)
Flattened_X = A.flatten()
print('the result of flattening A', Flattened_X)
print('flattening A with row major ordering',A.flatten(order="C"))
print('flattening A with column major ordering',A.flatten(order="F"))
print('flattening A preserving the C/Fortran style of the original array',A.flatten(order="A"))

This behaviour is true for both ```ravel``` and ```flatten.``` The important difference is that if we subsequently edit the values of ```Flattened_X``` (the output of the ```flatten()``` operation) the original array ```A``` remains unchanged. On the other hand, this is not the case with ```ravel```, which continues to point to the location of ```A``` in memory. Thus it's important to carefully consider which behaviour is desired.

In [ ]:

Flattened_X[0]=100
print('see that after flatten() any changes to the new array \n {} do not impact A \n {}'.format(Flattened_X,A))

B=A.ravel()
B[0]=200

print('On the other hand, changing the output of ravel (B): \n {} does change A \n {} this is because they point to the same location in memory'
      .format(B,A))



### 4.5.2 General reshaping

Alternatively, arrays can be reshaped to generic sizes using the ```reshape``` and ```resize``` functions. Here reshape creates a copy of the array, whereas resize modifies the original array

In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) 

new_A=A.reshape((2,6))
print('original shape: {}; new shape {} - note A retains its orginal shape'.format(A.shape,new_A.shape) ) 
print(new_A)           


# now resize the original array
A.resize((2,6))
print('note following resize the original array shape is changed however',A.shape)  

The numbers are resampled to the new shape following the order the array is stored in memory (generally C-style) 

### 4.5.3 Concatenation
It is also possible to create new arrays by concatenating two arrays, with (at least one) compatible dimension:

In [ ]:
B=np.random.randint(100,size=(2,6))

A_and_B=np.concatenate((A,B),axis=1) # first argument is a tuple containing arrays to be concatenated in order

print(B)
print(A_and_B)
print('shape of concatenated array',A_and_B.shape)


**Exercise** What happens when you change the axis of concatenation to 0?

Other operations for changing array shape and size can be found https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.array-manipulation.html

## 4. 6 Broadcasting

Broadcasting is a powerful mechanism within python that allows combined operations on arrays of (apparently) different sizes, provided the sizes of equivalent dimensions between arrays are either exactly the same or one. 

What this specifically means is if you have two arrays with different numbers of dimensions (e.g. a vector and a matrix), extra dimensions will be added to the smaller array to give it the same dimensionality e.g. and $1 \times n $ matrix rather than a length $n$ vector - shape (,$n$).

Then, effectively the smaller array will be copied along the new dimension as many times as is necessary until it has the exact same size as the larger array. Provided all other dimensions agree between the arrays, this will allow them to be operated on together .

For example, for summing a ```(3,4)``` shaped matrix with a ```(,4)``` shaped array; the Python IDE will broadcast 3 copies of of the vector in the row dimension until it has shape ```(3,4)```. This will allow the 2 arrays to be summed together:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11,12]])
v=np.array([10,20,30,40])
y = x + v  
print(y)  

# Exercise 2: Slicing, Reshaping and broadcasting

Try the suggested options on the below 3D array X:

1. Slice the third row, and second and 4th column 
    
2. Reshape X into a (6,4) matrix

3. What other configuration can you reshape X into?

4. Create a matrix one ones in the same size as X; concatenate with X

5. Create a new array of size (1,4,1) add it to X using broadcasting

6. Create an array of size (4,6) and add a row vector to it by broadcasting


In [4]:
X=np.array([[0, 1, 2],[3,4,5],[6,7,8], [9,10,11], [12,13,14], [15,16,17],[18,19,20],[21,22,23]])

# To do:  print X shape
print('X shape {}'.format(X.shape))

# 2.1 slice the third  and sizth row, with the second column to return a 2 x 1 array
print(X[[2,5],:1].shape) # note use of :1 in column index ensures return of 2x1 matrix raher than length 2 vector

# 2.2. reshape X into a (6,4) matrix
newX=X.reshape(6,4)
print('newX shape {}'.format(newX.shape))

# 2.3 What other configuration can you reshape X into?
print(X.reshape(3,8))
print(X.reshape(2,12))

# 2.4 Create a matrix one ones in the same size as X; concatenate with X first on rows then columns
my_ones=np.ones(X.shape)
my_concat=np.concatenate((my_ones,X))
print(' Shape after row concatenation {}'.format(my_concat.shape))
print(' Shape after row concatenation {}'.format(np.concatenate((my_ones,X),axis=1).shape))

# 2.5 Create a new array of size (1,3) add it to X using broadcasting
new=10*np.ones((1,3))
broadcasting_ex=new+X
print('result of broadcasted sum of \n {} \n with {} is \n {}'.format(X,new,broadcasting_ex))

# 2.6 Create an array of size (4,6) and add a row vector to it by broadcasting
A=np.random.randint(0,10,(4,6))
b=np.array([1,2,3,4,5,6])

print('A=',A)
print('A+b=',A+b)


X shape (8, 3)
(2, 1)
newX shape (6, 4)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
 Shape after row concatenation (16, 3)
 Shape after row concatenation (8, 6)
result of broadcasted sum of 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]] 
 with [[10. 10. 10.]] is 
 [[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]
 [19. 20. 21.]
 [22. 23. 24.]
 [25. 26. 27.]
 [28. 29. 30.]
 [31. 32. 33.]]
A= [[8 1 8 7 1 4]
 [7 7 4 9 6 4]
 [8 3 6 6 7 2]
 [1 2 0 0 6 2]]
A+b= [[ 9  3 11 11  6 10]
 [ 8  9  7 13 11 10]
 [ 9  5  9 10 12  8]
 [ 2  4  3  4 11  8]]


## 4.7 Array Operations

Numpy provides a vast array of different functions for operating on arrays. In this section we will introduce some of the most commonly used numpy functions, and those that will be used most in this course. 

Starting with some examples of elementwise operations. For these operators (```+,-,*,/``` etc) and have equivalent numpy functions (```add,subtract,multiply, divide```). Elementwise operations with scalars are also possible (essentially through broadcasting); see examples:

In [ ]:
# define arrays as floats; ensures results of operations are also expressed as floats

scalar=5
A = np.array([[1,2],[3,4]], dtype=np.float64) 
B = np.array([[10,20],[30,40]], dtype=np.float64)

# Elementwise sum; can use + or add
print('Elementwise sum between array {} and scalar {} using + : {}'.format(A,scalar,A + scalar))
print('Elementwise sum using + :')
print(A + B)
print('Elementwise sum using np.add:')
print(np.add(A, B))
# Elementwise difference; can use - or subtract
print('Elementwise subtract using - :')
print(A - B)
print('Elementwise sum using np.subtract :')
print(np.subtract(A, B))

# Elementwise product; can use * or multiple
print('Elementwise multiply using * :')
print(A * B)
print('Elementwise multiple using np.multiply :')
print(np.multiply(A, B))

# Elementwise division; can use \ or divide
print('Elementwise division using / :')
print(A/B)
print('Elementwise division using np.divide :')
print(np.divide(A,B))

Numpy also offers a comprehensive complement of matrix operations. However, it's important to be mindful about how each operates on vectors, matrices and higher dimensional tensors. 

For 1D arrays three different functions calculate the dot product: ```np.inner```, ```np.dot``` and ```np.matmul```. These functions start to diverge however at higher dimensions. Specifically the inner product (```np.inner```) returns the sum product of two matrices, whereas ```np.dot``` and ```np.matmul``` estimate the matrix product.

For two matrices $A$ and $B$ this means that ```np.inner``` will estimate the matrix product $AB^T$ (to multiply and sum corresponding elements from the rows of $A$ and rows of $B$, whereas ```np.dot``` and ```np.matmul``` estimate $AB$ (the literal matrix product of $A$ and $B$, multiplying and summing elements from the rows of $A$ and columns of $B$)

In [ ]:
a = np.array([1,2,3])
b = np.array([0,1,0])

# perform inner product 
# for vectors all three of these method return
# [a1b1,a2b2,a3b3]
print('inner product of vectors :')
print(np.inner(a,b))

print('dot product of vectors :')
print(np.dot(a,b))

print('matrix product of vectors :')
print(np.matmul(a,b))

# For 2D arrays inner returns the sum product
print('For matrices \n A={} \n B={} \n inner product={} '.format(A,B,np.inner(A,B)))

# whereas matmul and dot return matrix product
print('For matrices dot product= \n{} '.format(np.dot(A,B)))

print('For matrices matrix product= \n{} '.format(np.matmul(A,B)))


At higher dimensions ```np.dot``` and ```np.matmul``` diverge with ```np.dot(A,B)``` estimating the sum product between the last axis of A and the penultimate axis of B; whereas ```np.matmul(A,B)``` performs matrix multiplication assuming stacks of matrices. 

Regardless, the TL;DR of all this is that you are probably safest using ```np.matmul()``` for your matrix and vector multiplication operations. 

Other potentially useful matrix product operations are:

In [ ]:
# perform outer product  =
#[a1b1,a1b2,a1b3; 
# a2b1,a2b2,a2b3]
# a3b1,a3b2,a3b3]
print('outer product :')
print(np.outer(a,b))

# perform cross product  =
# [ (a2b3-b2a3) , (a1b3-b1a3), (a1b2-b1a2)] 
print('cross product :')
print(np.cross(a,b))

# estimating a matrix transpose 
print('matrix transpose:')
print(A.transpose()) # note here use of transpose as object attribute, equally accessible as np.transpose(A)



And, operations for matrix factorisation are available including methods for square (```eig```) and non-square matrices (cholesky, ```cholesky``` and singular value decompsition, ```svd```):

In [ ]:
# first estimate eigenvalues and vectors of a square matrix
# A=PQP^(-1) with eigenvalues (Q) and vectors (P)
mat1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Q,P=np.linalg.eig(mat1)
print('Eigenvalues of square matrix:',Q)
print('Eigenvectors of square matrix:')
print(P)

# now estimate eigenvalues and vectors of a non-square matrix using svd
# svd decomposition:
# A=UDV* (where V* is conjugate transpose of V ; U and V are the left and right singular vectors of A,
# D is a diagonal matrix conatining singular values)
mat2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11,12]])
u,d,v=np.linalg.svd(mat2)
print('Singular values of non-square matrix:',d)
print('left singular vectors of non-square matrix:')
print(u)
print('right singular vectors of non-square matrix:')
print(v)



More functions will be introduced over the course of the lecture series. However, for the full range of functions available from numpy please see the library manual: https://docs.scipy.org/doc/numpy-1.13.0/reference/index.html (in particular pages on mathematical functions https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html and linear algebra https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.linalg.html). Note, it is also straightforward to search for the functions you need online or through stackoverflow. 

# Exercise 3: Array Operations

Now try some array operations.

Some other potentially useful elementwise operations include ```mean, std, var, sum, sqrt, fabs, exp ``` and ```log```. These estimate the  mean, standard deviation, variance, sum, square root, absolute values, exponentials and natural logs of all elements in an array. Try some of these, and other examples (https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.math.html) below:

In [6]:
# define array with positives and negatives
C = np.array([[16,64],[-25,4]], dtype=np.float64) 

# estimate mean of matrix elements (replace `None` with correct numpy function call)
meanC=np.mean(C)
#or
meanC=C.mean()

# estimate the standard deviation and variance 
stdC=C.std()
varC=C.var()

# get absolute values 
fabsC=np.fabs(C) # not available as a class method

# estimate square root of fabsC
sqrtC=np.sqrt(fabsC) 

# estimate exponential of fabsC
expC=np.exp(fabsC)

# estimate natural log of fabsC
logC=np.log(fabsC)

# try some other functions 

# MATRIX OPERATIONS
# if you are getting confused consider comparing results against those obtained in matlab 

# create 2 3x3 matrices
A=np.random.randint(5,10,(3,3))
B=np.random.randint(1,5,(3,3))


# perform elementwise multiplication
elementwise=A*B

# perform matrix multiplication - use matmul or dot
matmul=np.dot(A,B)
matmul2=np.matmul(A,B)

print('dot product \n {} '.format(matmul))
print('matrix product \n {} '.format(matmul2))


# estimate the eigenvalues and vectors of one matrix
Q,P=np.linalg.eig(A)

dot product 
 [[41 52 76]
 [49 63 84]
 [37 47 68]] 
matrix product 
 [[41 52 76]
 [49 63 84]
 [37 47 68]] 


# Citation

Travis E, Oliphant. A guide to NumPy, USA: Trelgol Publishing, (2006).